### PR TITLE
Add no-proxy setting; provide useful error messages

### PR DESCRIPTION
**Pull request by jeffdolle-sge**
Added a rule for `$.proxy`, improved error messages by offering the native alternatives, added a short description explaining why this linter should be used, and check against `$` OR `jQuery` as the object name.

### CODE REVIEW

**Comment by dgraham** [comment]
Thanks, but there are too many changes in this branch to merge.

It’s true that jQuery is no longer required, but I don’t want to disparage it in the documentation. It’s a really great library that served us well for many years. This linter plugin is designed to help migrate jQuery calls to native web platform API in large codebases.

A pull request adding only the `$.proxy` rule is welcome.

**Comment by niksy** [comment]
I would like to propose to maybe implement this PR, but where every rule can have option which displays alternative for every rule, e.g.

```json
{
  "plugins": [
    "jquery"
  ],
  "rules": {
    "jquery/no-ajax": [2, {
        "displayAlternative": true
    }],
    "jquery/no-animate": [2, {
        "displayAlternative": true
    }],
    // ...
  }
}
```

It would mean you need to set it for every rule, but at least it’s more granular.

What do you think? @dgraham @jeffdolle-sge

**Comment by jeffdolle-sge** [comment]
I do think there should be more useful error messages, but I don't think those error messages should be configurable.

**Comment by niksy** [comment]
Don’t understand what you mean by "configurable", from what I can gather you would have two types of messages, default ones and ones which suggest alternative to jQuery method.

And regarding custom settings for rules, I just remembered that you can actually set preferred message inside `settings` object, so there’s no need to set it for every rule:

```json
{
    "settings": {
        "jquery": {
            "displayAlternative": true
        }
    }
}
```

**Pull request closed without merging**
